name: Notify on Upstream Commit

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch: # Allows manual trigger of the workflow

jobs:
  check-upstream:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Add Upstream Repository
        run: git remote add upstream https://github.com/cardano-foundation/cardano-token-registry.git

      - name: Fetch Upstream Branches
        run: git fetch upstream --prune

      - name: Get Default Branch of Upstream
        id: get_branch
        run: |
          DEFAULT_BRANCH=$(git remote show upstream | awk '/HEAD branch/ {print $NF}')
          echo "default_branch=$DEFAULT_BRANCH" >> $GITHUB_ENV

      - name: Check for New Commits
        id: check_commits
        run: |
          NEW_COMMITS=$(git log HEAD..upstream/$DEFAULT_BRANCH --oneline || echo "")
          echo "new_commits=$NEW_COMMITS" >> $GITHUB_ENV

      - name: Notify Discord
        if: env.new_commits != ''
        run: |
          curl -X POST -H "Content-Type: application/json" \
            -d '{"content": "New commits in upstream:\n```'"$NEW_COMMITS"'```"}' \
            ${{ secrets.DISCORD_WEBHOOK }}
