name: Sync Fork with Upstream

on:
  schedule:
    - cron: '*/5 * * * *' 
  workflow_dispatch: 

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Add Upstream
        run: |
          git remote add upstream https://github.com/cardano-foundation/cardano-token-registry.git
          git fetch upstream
          git checkout master
          git merge upstream/master
          
      - name: Push Changes
        run: |
          git push origin main
